Death link toggle setting, also slight clean up
DaftBrit/NoitaArchipelago pull request #142
Opened 2023-05-28 19:10 UTC by ScipioWright

Added a setting to let you disable death link if you regretted your decisions.

2023-05-28 23:58 UTC, heinermann requested changes
As it is in the code `ModSettingGet("archipelago.death_link")` means deathlink is disabled if false which is the default, I commented my thoughts to avoid the confusion.

2023-05-28 23:58 UTC, heinermann commented on init.lua
> +		if not slot_options.death_link or not ModSettingGet("archipelago.death_link") or not UpdateDeathTime() then return end
Let's do

```lua
local function IsDeathLinkEnabled()
   return slot_options.death_link and ModSettingGet("archipelago.death_link")
end
```

Then in these we check
```lua
if not IsDeathLinkEnabled() or not ...
```

2023-05-28 23:58 UTC, heinermann commented on init.lua
> +	if sock == nil or slot_options == nil or slot_options.death_link ~= 1 or not ModSettingGet("archipelago.death_link") or game_is_paused or not UpdateDeathTime() then return end
`slot_options` will be `nil` if `sock` is `nil`, in fact `sock` can't even be `nil` even if the initialization fails so we can get rid of the condition for `sock` to improve readability here. Plus with `IsDeathLinkEnabled` above should make it easier to read.

2023-05-28 23:58 UTC, heinermann commented on settings.lua
> +		en="Allows you to disable death link for future runs.\nDoes nothing if you did not enable death link in your yaml."
Would prefer "Allow Death Link" which defaults true just so that we don't have to deal with double-negatives and have to potentially misunderstand the meaning of the setting string `archipelago.death_link` .

Something like "Allow Death Link", desc: "If DeathLink is allowed, the deathlink setting in the archipelago YAML file will be used. If this is disabled, then it will override the YAML and disable deathlink."

2023-05-29 01:38 UTC, ScipioWright commented on settings.lua
> +		en="Allows you to disable death link for future runs.\nDoes nothing if you did not enable death link in your yaml."
Ahh there it is, I couldn't think of the word allow for some reason, or any word remotely similar.

2023-05-29 09:12 UTC, heinermann commented on settings.lua
> +		en="When enabled, the death link setting in your Archipelago YAML will be used.\nWhen disabled, this will override your YAML and disable death link in future runs."
If we change it to `MOD_SETTING_SCOPE_RUNTIME` it should also be able to be changed at any point as well right? Since it checks it every time a death is received or if you die.

2023-05-29 15:56 UTC, ScipioWright commented on settings.lua
> +		en="When enabled, the death link setting in your Archipelago YAML will be used.\nWhen disabled, this will override your YAML and disable death link in future runs."
I was thinking that would be a little too nice? I dunno, I could go either way on it. Which do you think would be better?

2023-05-30 06:52 UTC, heinermann commented on settings.lua
> +		en="When enabled, the death link setting in your Archipelago YAML will be used.\nWhen disabled, this will override your YAML and disable death link in future runs."
I think there could be a case where someone forgets, changes it, then expects it to have worked and it doesn't could cause them to report it as an issue.

2023-05-30 14:24 UTC, ScipioWright commented on settings.lua
> +		en="When enabled, the death link setting in your Archipelago YAML will be used.\nWhen disabled, this will override your YAML and disable death link in future runs."
Yeah, reasonable enough then -- I've changed it. And anyway, if it was set to new game, people could still skirt by the death link by clicking new game when they're about to die, so whatever.

2023-05-30 19:13 UTC, heinermann approved these changes

2023-05-30 19:13 UTC, merged